### ISSUE TITLE
Command failed: WSLHostPatcher.exe

### ISSUE THREAD

**Issue by staff0rd** [icflorescu/expose-wsl#5] opened 2023-07-05 15:10 UTC
After getting #3 and installing `unzip`, the command still fails:

```
stafford@deskt0p:~$ npx expose-wsl@latest
Need to install the following packages:
  expose-wsl@1.0.23
Ok to proceed? (y) y
                                                   _
   _____  ___ __   ___  ___  ___     __      _____| |
  / _ \ \/ / '_ \ / _ \/ __|/ _ \____\ \ /\ / / __| |
 |  __/>  <| |_) | (_) \__ \  __/_____\ V  V /\__ \ |
  \___/_/\_\ .__/ \___/|___/\___|      \_/\_/ |___/_|
           |_|

⏳ Patching WSL... node:internal/errors:867
  const err = new Error(message);
              ^

Error: Command failed: /home/stafford/.npm/_npx/0e95d415fb20f5d8/node_modules/expose-wsl/WSLHostPatcher.exe
    at checkExecSyncError (node:child_process:885:11)
    at execSync (node:child_process:957:15)
    at file:///home/stafford/.npm/_npx/0e95d415fb20f5d8/node_modules/expose-wsl/run.js:28:1
    at ModuleJob.run (node:internal/modules/esm/module_job:194:25) {
  status: 255,
  signal: null,
  output: [
    null,
    Buffer(135) [Uint8Array] [
       68, 108, 108,  32, 112,  97, 116, 104,  58,  32,  92,  92,
      119, 115, 108,  46, 108, 111,  99,  97, 108, 104, 111, 115,
      116,  92,  85,  98, 117, 110, 116, 117,  92, 104, 111, 109,
      101,  92, 115, 116,  97, 102, 102, 111, 114, 100,  92,  46,
      110, 112, 109,  92,  95, 110, 112, 120,  92,  48, 101,  57,
       53, 100,  52,  49,  53, 102,  98,  50,  48, 102,  53, 100,
       56,  92, 110, 111, 100, 101,  95, 109, 111, 100, 117, 108,
      101, 115,  92, 101, 120, 112, 111, 115, 101,  45, 119, 115,
      108,  92,  87,  83,
      ... 35 more items
    ],
    Buffer(0) [Uint8Array] []
  ],
  pid: 8869,
  stdout: Buffer(135) [Uint8Array] [
     68, 108, 108,  32, 112,  97, 116, 104,  58,  32,  92,  92,
    119, 115, 108,  46, 108, 111,  99,  97, 108, 104, 111, 115,
    116,  92,  85,  98, 117, 110, 116, 117,  92, 104, 111, 109,
    101,  92, 115, 116,  97, 102, 102, 111, 114, 100,  92,  46,
    110, 112, 109,  92,  95, 110, 112, 120,  92,  48, 101,  57,
     53, 100,  52,  49,  53, 102,  98,  50,  48, 102,  53, 100,
     56,  92, 110, 111, 100, 101,  95, 109, 111, 100, 117, 108,
    101, 115,  92, 101, 120, 112, 111, 115, 101,  45, 119, 115,
    108,  92,  87,  83,
    ... 35 more items
  ],
  stderr: Buffer(0) [Uint8Array] []
}

Node.js v18.16.1
```

Ubuntu 22.04.2 LTS

**Comment by niconiconi1234** [comment] 2023-07-18 17:13
same problem on Windows 11 Pro and Ubuntu 22.04 LTS via WSL

**Comment by icflorescu** [comment] 2023-07-19 15:03
I'm afraid I can't reproduce the problem on my setup. Everything seems to be working fine on Windows 11 with Ubuntu 22.

@niconiconi1234 - Are you sure you have `unzip` installed?
@staff0rd - Can you tell me your `node` & `npm` versions, please?

**Comment by staff0rd** [comment] 2023-07-20 04:07
oddly, just now, on a WSL instance that i've been running `expose-wsl` on for weeks without issue, I got the same problem.

```
$ npm --version
9.5.1
$ node --version
v18.16.1
```

**Comment by staff0rd** [comment] 2023-07-20 04:17
Took a look at the source and found this is a wrapper/downloader for [CzBiX/WSLHostPatcher](https://github.com/CzBiX/WSLHostPatcher). Using the approach in that repo (manually downloading `WSLHostPatcher.exe` and calling it from `.profile`) is a workable approach for me.

I'll leave the issue open for others, but I'm unlikely to follow this one further. Great tool, thanks for your efforts @icflorescu.

**Comment by icflorescu** [comment] 2023-08-04 13:12
Hopefully this is fixed in the latest version.
Feel free to reopen if necessary.

**Closed as completed by icflorescu** 2023-08-04 13:12 UTC
